const activities = [
  // Nature theme
  {
    id: '1',
    title: 'Sunset Viewpoint',
    description: 'Stunning panoramic views of the city',
    fullDescription: 'A hidden gem offering breathtaking sunset views. Best visited during golden hour for photography. The viewpoint is accessible via a short walk and offers 360-degree views of the surrounding landscape.',
    photo: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    photos: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
      'https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=800',
      'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800',
    ],
    category: 'Spot',
    activityType: 'solo',
    vibe: ['Scenic', 'Quiet'],
    timeContext: 'Best at sunset',
    indoor: false,
    distance: '2.3 km',
    savedByCount: 142,
    goodFor: ['Photography', 'Relaxing', 'Solo time'],
    location: 'Hilltop Park',
    costLevel: 'Free',
    averageRating: 4.7,
    totalRatings: 89,
    communityPhotos: [],
    threads: [],
    currentConditions: {
      crowdLevel: 'Low crowd now',
      atmosphere: 'Peaceful',
      lightCondition: 'Soft light now',
    },
    specialMoment: 'Best at 18:15 for sunset',
    contentType: 'standard',
    subTheme: 'Sunset Spots',
    themeId: 'nature',
  },
  {
    id: '2',
    title: 'Eagle Peak Trail',
    description: 'Moderate hiking trail with forest views',
    fullDescription: 'A beautiful 5km trail through dense forest with occasional clearings. Perfect for intermediate hikers looking for a half-day adventure.',
    photo: 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=800',
    photos: [
      'https://images.unsplash.com/photo-1551632811-561732d1e306?w=800',
      'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800',
      'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800',
    ],
    category: 'Activity',
    activityType: 'active-social',
    vibe: ['Active', 'Nature'],
    timeContext: 'Great for morning hikes',
    indoor: false,
    distance: '5.8 km',
    savedByCount: 231,
    goodFor: ['Hiking', 'Exercise', 'Nature'],
    location: 'Eagle Peak',
    costLevel: 'Free',
    averageRating: 4.5,
    totalRatings: 156,
    communityPhotos: [],
    threads: [],
    currentConditions: {
      crowdLevel: 'Moderate',
      atmosphere: 'Energetic',
      walkingCondition: 'Moderate incline',
    },
    contentType: 'route',
    route: {
      distance: '5.2 km',
      duration: '2.5 hours',
      difficulty: 'Moderate',
      elevation: '350m',
      startPoint: 'Eagle Peak Trailhead',
      waypoints: [],
    },
    subTheme: 'Day Hikes',
    themeId: 'routes',
  },
  {
    id: '3',
    title: 'Blue Bottle Coffee',
    description: 'Cozy café perfect for focused work',
    fullDescription: 'Minimalist café with excellent coffee and fast WiFi. Gets busy after lunch. Perfect spot for remote work or studying.',
    photo: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800',
    photos: [
      'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800',
      'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800',
    ],
    category: 'Spot',
    activityType: 'solo',
    vibe: ['Cozy', 'Quiet'],
    timeContext: 'Quiet in mornings',
    indoor: true,
    distance: '0.8 km',
    savedByCount: 89,
    goodFor: ['Study', 'Work', 'Coffee'],
    location: 'Downtown',
    costLevel: '$$',
    averageRating: 4.6,
    totalRatings: 234,
    communityPhotos: [],
    threads: [],
    currentConditions: {
      crowdLevel: 'Low crowd now',
      atmosphere: 'Calm',
    },
    contentType: 'standard',
    subTheme: 'Study Spots',
    themeId: 'cafes',
  },
  {
    id: '4',
    title: 'Golden Gate Viewpoint',
    description: 'Perfect spot for sunrise photography',
    fullDescription: 'This iconic viewpoint offers stunning views of the Golden Gate Bridge. Best visited at sunrise for optimal lighting and fewer crowds.',
    photo: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800',
    photos: [
      'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800',
      'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800',
    ],
    category: 'Spot',
    activityType: 'solo',
    vibe: ['Scenic', 'Peaceful'],
    timeContext: 'Sunrise',
    indoor: false,
    distance: '2.3 km',
    savedByCount: 245,
    goodFor: ['Photography', 'Sightseeing'],
    location: 'San Francisco',
    costLevel: 'Free',
    averageRating: 4.8,
    totalRatings: 120,
    communityPhotos: [],
    threads: [],
    currentConditions: {
      crowdLevel: 'Quiet',
      atmosphere: 'Calm',
      lightCondition: 'Golden Hour',
    },
    specialMoment: 'Best at sunrise',
    themeId: 'photography',
    subTheme: 'Viewpoints',
  },
  {
    id: '5',
    title: 'Urban Coffee Roasters',
    description: 'Artisanal coffee and great wifi',
    fullDescription: 'A cozy cafe perfect for working and meetings. Features locally roasted coffee and comfortable seating.',
    photo: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800',
    photos: [
      'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800',
      'https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800',
    ],
    category: 'Activity',
    activityType: 'passive-social',
    vibe: ['Cozy', 'Productive'],
    timeContext: 'Morning',
    indoor: true,
    distance: '0.8 km',
    savedByCount: 189,
    goodFor: ['Work', 'Coffee'],
    location: 'Downtown',
    costLevel: '$$',
    averageRating: 4.6,
    totalRatings: 95,
    communityPhotos: [],
    threads: [],
    currentConditions: {
      crowdLevel: 'Moderate',
      atmosphere: 'Productive',
    },
    themeId: 'cafes',
    subTheme: 'Coffee Shops',
  },
  {
    id: '6',
    title: 'Twin Peaks Sunset Hike',
    description: '360° views of the city',
    fullDescription: 'Popular hiking spot with panoramic city views. The trail is well-maintained and suitable for all fitness levels.',
    photo: 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=800',
    photos: [
      'https://images.unsplash.com/photo-1551632811-561732d1e306?w=800',
      'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800',
    ],
    category: 'Route',
    activityType: 'active-social',
    vibe: ['Active', 'Scenic'],
    timeContext: 'Sunset',
    indoor: false,
    distance: '4.1 km',
    savedByCount: 312,
    goodFor: ['Hiking', 'Photography'],
    location: 'Twin Peaks',
    costLevel: 'Free',
    averageRating: 4.9,
    totalRatings: 180,
    communityPhotos: [],
    threads: [],
    currentConditions: {
      crowdLevel: 'Busy',
      atmosphere: 'Energetic',
      lightCondition: 'Golden Hour',
    },
    bestTimeToVisit: 'Sunset (5-7 PM)',
    route: {
      distance: '2.5 km',
      duration: '45 min',
      difficulty: 'Moderate',
      elevation: '+150m',
      startPoint: 'Twin Peaks Parking',
      waypoints: [],
    },
    themeId: 'routes',
    subTheme: 'Scenic Loops',
  },
  {
    id: '7',
    title: 'Dolores Park Picnic',
    description: 'Popular gathering spot with city views',
    fullDescription: 'A vibrant park perfect for picnics and socializing. Features great views and plenty of space for groups.',
    photo: 'https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?w=800',
    photos: [
      'https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?w=800',
      'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800',
    ],
    category: 'Spot',
    activityType: 'active-social',
    vibe: ['Social', 'Relaxed'],
    timeContext: 'Afternoon',
    indoor: false,
    distance: '1.6 km',
    savedByCount: 425,
    goodFor: ['Picnic', 'Socializing'],
    location: 'Mission District',
    costLevel: 'Free',
    averageRating: 4.7,
    totalRatings: 210,
    communityPhotos: [],
    threads: [],
    currentConditions: {
      crowdLevel: 'Very Busy',
      atmosphere: 'Lively',
    },
    specialMoment: 'Weekends are buzzing',
    themeId: 'social',
    subTheme: 'Meetups',
  },
  {
    id: '8',
    title: 'Ocean Beach Sunset',
    description: 'Watch the waves and sunset',
    fullDescription: 'Beautiful beach perfect for sunset walks. The wide sandy beach offers plenty of space even on busy days.',
    photo: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
    photos: [
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
    ],
    category: 'Spot',
    activityType: 'solo',
    vibe: ['Peaceful', 'Scenic'],
    timeContext: 'Sunset',
    indoor: false,
    distance: '6.2 km',
    savedByCount: 389,
    goodFor: ['Walking', 'Photography'],
    location: 'Outer Sunset',
    costLevel: 'Free',
    averageRating: 4.8,
    totalRatings: 165,
    communityPhotos: [],
    threads: [],
    currentConditions: {
      crowdLevel: 'Moderate',
      atmosphere: 'Peaceful',
      lightCondition: 'Golden Hour',
    },
    bestTimeToVisit: 'Sunset (6-8 PM)',
    themeId: 'water',
    subTheme: 'Beaches',
  },
  {
    id: '9',
    title: 'Mountain Lake Park',
    description: 'Serene lake surrounded by trails',
    fullDescription: 'A peaceful lake perfect for morning walks or afternoon relaxation. The surrounding trails offer great views.',
    photo: 'https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?w=800',
    photos: [
      'https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?w=800',
      'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800',
    ],
    category: 'Spot',
    activityType: 'solo',
    vibe: ['Peaceful', 'Nature'],
    timeContext: 'Anytime',
    indoor: false,
    distance: '3.5 km',
    savedByCount: 156,
    goodFor: ['Walking', 'Nature', 'Relaxing'],
    location: 'Presidio',
    costLevel: 'Free',
    averageRating: 4.6,
    totalRatings: 98,
    communityPhotos: [],
    threads: [],
    currentConditions: {
      crowdLevel: 'Low',
      atmosphere: 'Tranquil',
    },
    themeId: 'nature',
    subTheme: 'Lakes & Swim',
  },
  {
    id: '10',
    title: 'Yoga in the Park',
    description: 'Community yoga sessions every Saturday',
    fullDescription: 'Join the community for free yoga sessions in the park. All levels welcome. Bring your own mat.',
    photo: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800',
    photos: [
      'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800',
      'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800',
    ],
    category: 'Activity',
    activityType: 'active-social',
    vibe: ['Active', 'Social'],
    timeContext: 'Saturday mornings',
    indoor: false,
    distance: '1.2 km',
    savedByCount: 203,
    goodFor: ['Exercise', 'Socializing', 'Wellness'],
    location: 'Golden Gate Park',
    costLevel: 'Free',
    averageRating: 4.8,
    totalRatings: 145,
    communityPhotos: [],
    threads: [],
    currentConditions: {
      crowdLevel: 'Moderate',
      atmosphere: 'Energizing',
    },
    themeId: 'sport',
    subTheme: 'Yoga',
  },
];

const themes = [
  {
    id: 'nature',
    name: 'Nature',
    shortDescription: 'Outdoors & Parks',
    description: 'Explore outdoor spots and scenic locations',
    image: 'https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?w=600',
    gradient: 'from-green-400 to-emerald-600',
    icon: '🌲',
    subThemes: ['Hikes', 'Forest Walks', 'Scenic Views', 'Lakes & Swim', 'Sunset Spots'],
  },
  {
    id: 'sport',
    name: 'Sport',
    shortDescription: 'Fitness & Activity',
    description: 'Find fitness activities and workout spots',
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600',
    gradient: 'from-orange-400 to-red-600',
    icon: '⚽',
    subThemes: ['Gyms', 'Yoga', 'Running Routes', 'Sports Fields', 'Climbing'],
  },
  {
    id: 'photography',
    name: 'Photography',
    shortDescription: 'Viewpoints & Shots',
    description: 'Discover the best spots for photos',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600',
    gradient: 'from-purple-400 to-pink-600',
    icon: '📸',
    subThemes: ['Viewpoints', 'Architecture', 'Street', 'Nature', 'Golden Hour'],
  },
  {
    id: 'cafes',
    name: 'Cafés & Study',
    shortDescription: 'Coffee & Work',
    description: 'Cozy spots for coffee and work',
    image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600',
    gradient: 'from-amber-400 to-orange-600',
    icon: '☕',
    subThemes: ['Coffee Shops', 'Study Spots', 'Co-working', 'Quiet Cafés', 'WiFi'],
  },
  {
    id: 'social',
    name: 'Social',
    shortDescription: 'Meetups & Events',
    description: 'Meet people and join group activities',
    image: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=600',
    gradient: 'from-blue-400 to-cyan-600',
    icon: '🎉',
    subThemes: ['Meetups', 'Events', 'Group Activities', 'Social Sports', 'Workshops'],
  },
  {
    id: 'water',
    name: 'Water & Swim',
    shortDescription: 'Lakes & Beaches',
    description: 'Swimming and water activities',
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600',
    gradient: 'from-cyan-400 to-blue-600',
    icon: '🏊',
    subThemes: ['Lakes', 'Beaches', 'Pools', 'Rivers', 'Water Sports'],
  },
  {
    id: 'routes',
    name: 'Routes & Hikes',
    shortDescription: 'Trails & Walks',
    description: 'Walking and hiking trails',
    image: 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=600',
    gradient: 'from-teal-400 to-green-600',
    icon: '🥾',
    subThemes: ['Easy Walks', 'Day Hikes', 'Mountain Trails', 'Urban Routes', 'Scenic Loops'],
  },
  {
    id: 'seasonal',
    name: 'Seasonal',
    shortDescription: 'Limited Time',
    description: 'Limited-time activities and experiences',
    image: 'https://images.unsplash.com/photo-1476820865390-c52aeebb9891?w=600',
    gradient: 'from-rose-400 to-pink-600',
    icon: '🍂',
    subThemes: ['Winter', 'Spring', 'Summer', 'Fall', 'Festivals'],
  },
  {
    id: 'hidden',
    name: 'Hidden Gems',
    shortDescription: 'Off the Beaten Path',
    description: 'Off-the-beaten-path discoveries',
    image: 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=600',
    gradient: 'from-indigo-400 to-purple-600',
    icon: '💎',
    subThemes: ['Local Secrets', 'Quiet Spots', 'Undiscovered', 'Unique', 'Insider Tips'],
  },
];

const users = {
  currentUser: {
    id: 'user1',
    name: 'Jordan Smith',
    avatar: 'https://i.pravatar.cc/150?u=jordan',
    bio: 'Exploring the city one adventure at a time ✨',
    joinDate: 'Nov 2024',
    city: 'San Francisco',
    interests: ['Photography', 'Hiking', 'Coffee', 'Nature'],
    isOwnProfile: true,
    stats: {
      photos: 24,
      activities: 12,
      threads: 8,
    },
  },
};

const messages = [
  {
    activityId: '1',
    messages: [
      {
        id: '1',
        userId: 'user1',
        userName: 'Sarah Chen',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
        message: 'Hey! Planning to go this weekend, anyone interested?',
        timestamp: '10:30 AM',
      },
      {
        id: '2',
        userId: 'user2',
        userName: 'Alex Martinez',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
        message: 'I\'m down! What time were you thinking?',
        timestamp: '10:45 AM',
      },
      {
        id: '3',
        userId: 'user1',
        userName: 'Sarah Chen',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
        message: 'Around 9 AM? The weather looks perfect ☀️',
        timestamp: '10:47 AM',
      },
      {
        id: '4',
        userId: 'user3',
        userName: 'Jordan Lee',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jordan',
        message: 'Can I join too? First time trying this!',
        timestamp: '11:02 AM',
      },
      {
        id: '5',
        userId: 'user2',
        userName: 'Alex Martinez',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
        message: 'Of course! We can meet at the entrance',
        timestamp: '11:15 AM',
      },
    ],
  },
  {
    activityId: '3',
    messages: [
      {
        id: '6',
        userId: 'user4',
        userName: 'Emma Wilson',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
        message: 'Great spot! I\'ll be there today',
        timestamp: '1 hour ago',
      },
    ],
  },
];

const savedActivities = [
  activities[0], // Sunset Viewpoint
  activities[3], // Golden Gate Viewpoint
  activities[5], // Twin Peaks Sunset Hike
];

module.exports = {
  activities,
  themes,
  users,
  messages,
  savedActivities,
};

