// Helper to generate relative timestamps
const getRelativeTime = (hoursAgo) => {
  const date = new Date();
  date.setHours(date.getHours() - hoursAgo);
  return date.toISOString();
};

// Enhanced user profiles
const userProfiles = [
  {
    id: 'user1',
    name: 'Jordan Smith',
    username: '@jordansmith',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jordan',
    bio: 'Adventure seeker 🏔️ | Coffee enthusiast ☕',
    joinedDate: '2024-08-15',
    followersCount: 342,
    followingCount: 189,
    activitiesCount: 56,
  },
  {
    id: 'user2',
    name: 'Sarah Chen',
    username: '@sarahchen',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    bio: 'Photographer | Nature lover 🌲',
    joinedDate: '2024-06-20',
    followersCount: 521,
    followingCount: 234,
    activitiesCount: 89,
  },
  {
    id: 'user3',
    name: 'Alex Martinez',
    username: '@alexmartinez',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
    bio: 'Urban explorer | Fitness junkie 💪',
    joinedDate: '2024-09-10',
    followersCount: 278,
    followingCount: 156,
    activitiesCount: 42,
  },
  {
    id: 'user4',
    name: 'Emma Wilson',
    username: '@emmawilson',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
    bio: 'Digital nomad ✈️ | Yoga instructor',
    joinedDate: '2024-07-05',
    followersCount: 612,
    followingCount: 301,
    activitiesCount: 73,
  },
  {
    id: 'user5',
    name: 'Marcus Johnson',
    username: '@marcusj',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Marcus',
    bio: 'Trail runner 🏃 | Weekend warrior',
    joinedDate: '2024-05-12',
    followersCount: 445,
    followingCount: 198,
    activitiesCount: 91,
  },
  {
    id: 'user6',
    name: 'Olivia Park',
    username: '@oliviapark',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Olivia',
    bio: 'Food & travel blogger 🍜',
    joinedDate: '2024-04-22',
    followersCount: 834,
    followingCount: 423,
    activitiesCount: 127,
  },
  {
    id: 'user7',
    name: 'David Kim',
    username: '@davidkim',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
    bio: 'Software engineer | Climbing enthusiast 🧗',
    joinedDate: '2024-03-18',
    followersCount: 289,
    followingCount: 167,
    activitiesCount: 48,
  },
  {
    id: 'user8',
    name: 'Sophia Taylor',
    username: '@sophiataylor',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sophia',
    bio: 'Artist 🎨 | Sunset chaser',
    joinedDate: '2024-10-01',
    followersCount: 591,
    followingCount: 345,
    activitiesCount: 62,
  },
];

const activities = [
  // NATURE THEME - Hikes & Views (10+ activities)
  {
    id: '1',
    title: 'Sunset Viewpoint',
    description: 'Stunning panoramic views of the city',
    fullDescription: 'A hidden gem offering breathtaking sunset views. Best visited during golden hour for photography. The viewpoint is accessible via a short walk and offers 360-degree views of the surrounding landscape.',
    photo: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    photos: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
      'https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=800',
      'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800',
    ],
    category: 'Spot',
    activityType: 'solo',
    vibe: ['Scenic', 'Quiet'],
    timeContext: 'Best at sunset',
    indoor: false,
    distance: '2.3 km',
    savedByCount: 342,
    likesCount: 567,
    commentsCount: 89,
    goodFor: ['Photography', 'Relaxing', 'Solo time'],
    location: 'Hilltop Park',
    coordinates: { lat: 37.7749, lng: -122.4194 },
    costLevel: 'Free',
    averageRating: 4.7,
    totalRatings: 289,
    communityPhotos: [
      { id: 'cp1', url: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=400', userId: 'user2', userName: 'Sarah Chen', timestamp: getRelativeTime(24) },
      { id: 'cp2', url: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=400', userId: 'user4', userName: 'Emma Wilson', timestamp: getRelativeTime(72) },
    ],
    threads: [],
    currentConditions: {
      crowdLevel: 'Low crowd now',
      atmosphere: 'Peaceful',
      lightCondition: 'Soft light now',
    },
    specialMoment: 'Best at 18:15 for sunset',
    contentType: 'standard',
    subTheme: 'Sunset Spots',
    themeId: 'nature',
    createdBy: 'user2',
    createdAt: getRelativeTime(240),
  },
  {
    id: '2',
    title: 'Eagle Peak Trail',
    description: 'Moderate hiking trail with forest views',
    fullDescription: 'A beautiful 5km trail through dense forest with occasional clearings. Perfect for intermediate hikers looking for a half-day adventure.',
    photo: 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=800',
    photos: [
      'https://images.unsplash.com/photo-1551632811-561732d1e306?w=800',
      'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800',
      'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800',
    ],
    category: 'Activity',
    activityType: 'active-social',
    vibe: ['Active', 'Nature'],
    timeContext: 'Great for morning hikes',
    indoor: false,
    distance: '5.8 km',
    savedByCount: 431,
    likesCount: 789,
    commentsCount: 156,
    goodFor: ['Hiking', 'Exercise', 'Nature'],
    location: 'Eagle Peak',
    coordinates: { lat: 37.8044, lng: -122.4412 },
    costLevel: 'Free',
    averageRating: 4.5,
    totalRatings: 256,
    communityPhotos: [
      { id: 'cp3', url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=400', userId: 'user5', userName: 'Marcus Johnson', timestamp: getRelativeTime(48) },
    ],
    threads: [],
    currentConditions: {
      crowdLevel: 'Moderate',
      atmosphere: 'Energetic',
      walkingCondition: 'Moderate incline',
    },
    contentType: 'route',
    route: {
      distance: '5.2 km',
      duration: '2.5 hours',
      difficulty: 'Moderate',
      elevation: '350m',
      startPoint: 'Eagle Peak Trailhead',
      waypoints: [],
    },
    subTheme: 'Day Hikes',
    themeId: 'nature',
    createdBy: 'user5',
    createdAt: getRelativeTime(360),
  },
  {
    id: 'n3',
    title: 'Redwood Grove Loop',
    description: 'Easy walk through ancient redwoods',
    fullDescription: 'Peaceful 3km loop through towering redwood trees. Family-friendly with well-maintained paths.',
    photo: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800',
    photos: [
      'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800',
      'https://images.unsplash.com/photo-1448375240586-882707db888b?w=800',
    ],
    category: 'Route',
    activityType: 'passive-social',
    vibe: ['Peaceful', 'Nature'],
    timeContext: 'Morning mist',
    indoor: false,
    distance: '3.2 km',
    savedByCount: 289,
    likesCount: 512,
    commentsCount: 67,
    goodFor: ['Walking', 'Nature', 'Family'],
    location: 'Redwood Regional Park',
    coordinates: { lat: 37.8186, lng: -122.1586 },
    costLevel: '$5 parking',
    averageRating: 4.8,
    totalRatings: 198,
    communityPhotos: [],
    threads: [],
    currentConditions: {
      crowdLevel: 'Low',
      atmosphere: 'Serene',
    },
    contentType: 'route',
    route: {
      distance: '3.2 km',
      duration: '1 hour',
      difficulty: 'Easy',
      elevation: '50m',
      startPoint: 'Redwood Gate',
      waypoints: [],
    },
    subTheme: 'Forest Walks',
    themeId: 'nature',
    createdBy: 'user4',
    createdAt: getRelativeTime(480),
  },
  {
    id: 'n4',
    title: 'Mount Diablo Summit',
    description: 'Challenging climb with 360° views',
    fullDescription: 'Demanding 10km hike to the summit. Offers unparalleled views of the Bay Area on clear days.',
    photo: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    photos: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
      'https://images.unsplash.com/photo-1454496522488-7a8e488e8606?w=800',
    ],
    category: 'Route',
    activityType: 'active-social',
    vibe: ['Active', 'Challenging'],
    timeContext: 'Early morning start',
    indoor: false,
    distance: '10.5 km',
    savedByCount: 567,
    likesCount: 923,
    commentsCount: 234,
    goodFor: ['Hiking', 'Exercise', 'Views'],
    location: 'Mount Diablo State Park',
    coordinates: { lat: 37.8816, lng: -121.9142 },
    costLevel: '$10 parking',
    averageRating: 4.9,
    totalRatings: 412,
    communityPhotos: [
      { id: 'cp4', url: 'https://images.unsplash.com/photo-1519904981063-b0cf448d479e?w=400', userId: 'user5', userName: 'Marcus Johnson', timestamp: getRelativeTime(96) },
      { id: 'cp5', url: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400', userId: 'user3', userName: 'Alex Martinez', timestamp: getRelativeTime(120) },
    ],
    threads: [],
    currentConditions: {
      crowdLevel: 'Low',
      atmosphere: 'Challenging',
      weather: 'Clear skies',
    },
    contentType: 'route',
    route: {
      distance: '10.5 km',
      duration: '4-5 hours',
      difficulty: 'Hard',
      elevation: '1000m',
      startPoint: 'Mitchell Canyon Trailhead',
      waypoints: [],
    },
    subTheme: 'Day Hikes',
    themeId: 'nature',
    createdBy: 'user5',
    createdAt: getRelativeTime(600),
  },
  {
    id: 'n5',
    title: 'Crystal Springs Reservoir',
    description: 'Scenic lakeside trail for running or walking',
    fullDescription: 'Beautiful paved trail alongside the reservoir. Perfect for runners, cyclists, and walkers.',
    photo: 'https://images.unsplash.com/photo-1439066615861-d1af74d74000?w=800',
    photos: [
      'https://images.unsplash.com/photo-1439066615861-d1af74d74000?w=800',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    ],
    category: 'Route',
    activityType: 'solo',
    vibe: ['Active', 'Scenic'],
    timeContext: 'Anytime',
    indoor: false,
    distance: '8.4 km',
    savedByCount: 398,
    likesCount: 645,
    commentsCount: 112,
    goodFor: ['Running', 'Cycling', 'Walking'],
    location: 'Crystal Springs',
    coordinates: { lat: 37.5010, lng: -122.3417 },
    costLevel: 'Free',
    averageRating: 4.6,
    totalRatings: 267,
    communityPhotos: [],
    threads: [],
    currentConditions: {
      crowdLevel: 'Moderate',
      atmosphere: 'Active',
    },
    contentType: 'route',
    route: {
      distance: '8.4 km',
      duration: '1.5 hours walking',
      difficulty: 'Easy',
      elevation: '20m',
      startPoint: 'Pulgas Ridge Gate',
      waypoints: [],
    },
    subTheme: 'Scenic Views',
    themeId: 'nature',
    createdBy: 'user3',
    createdAt: getRelativeTime(720),
  },

  // CAFES THEME (8+ activities)
  {
    id: '3',
    title: 'Blue Bottle Coffee',
    description: 'Cozy café perfect for focused work',
    fullDescription: 'Minimalist café with excellent coffee and fast WiFi. Gets busy after lunch.',
    photo: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800',
    photos: [
      'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800',
      'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800',
    ],
    category: 'Spot',
    activityType: 'solo',
    vibe: ['Cozy', 'Quiet'],
    timeContext: 'Quiet in mornings',
    indoor: true,
    distance: '0.8 km',
    savedByCount: 189,
    likesCount: 423,
    commentsCount: 78,
    goodFor: ['Study', 'Work', 'Coffee'],
    location: 'Downtown',
    coordinates: { lat: 37.7849, lng: -122.4094 },
    costLevel: '$$',
    averageRating: 4.6,
    totalRatings: 334,
    communityPhotos: [],
    threads: [],
    currentConditions: {
      crowdLevel: 'Low crowd now',
      atmosphere: 'Calm',
    },
    contentType: 'standard',
    subTheme: 'Study Spots',
    themeId: 'cafes',
    createdBy: 'user7',
    createdAt: getRelativeTime(192),
  },
  {
    id: 'c2',
    title: 'Urban Coffee Roasters',
    description: 'Artisanal coffee and great wifi',
    fullDescription: 'A cozy cafe perfect for working and meetings. Features locally roasted coffee.',
    photo: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800',
    photos: [
      'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800',
      'https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800',
    ],
    category: 'Activity',
    activityType: 'passive-social',
    vibe: ['Cozy', 'Productive'],
    timeContext: 'Morning',
    indoor: true,
    distance: '1.2 km',
    savedByCount: 234,
    likesCount: 456,
    commentsCount: 92,
    goodFor: ['Work', 'Coffee', 'Meetings'],
    location: 'Mission District',
    coordinates: { lat: 37.7599, lng: -122.4148 },
    costLevel: '$$',
    averageRating: 4.5,
    totalRatings: 187,
    communityPhotos: [],
    threads: [],
    currentConditions: {
      crowdLevel: 'Moderate',
      atmosphere: 'Productive',
    },
    contentType: 'standard',
    subTheme: 'Coffee Shops',
    themeId: 'cafes',
    createdBy: 'user6',
    createdAt: getRelativeTime(288),
  },
  {
    id: 'c3',
    title: 'The Mill',
    description: 'Iconic SF bakery & coffee bar',
    fullDescription: 'Famous for their thick-cut toast and specialty coffee. Industrial-chic space with communal tables.',
    photo: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800',
    photos: [
      'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800',
      'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800',
    ],
    category: 'Spot',
    activityType: 'passive-social',
    vibe: ['Trendy', 'Social'],
    timeContext: 'Weekend brunch',
    indoor: true,
    distance: '2.1 km',
    savedByCount: 567,
    likesCount: 892,
    commentsCount: 156,
    goodFor: ['Brunch', 'Coffee', 'Socializing'],
    location: 'Alamo Square',
    coordinates: { lat: 37.7756, lng: -122.4353 },
    costLevel: '$$',
    averageRating: 4.7,
    totalRatings: 412,
    communityPhotos: [
      { id: 'cp7', url: 'https://images.unsplash.com/photo-1509785307050-d4066910ec1e?w=400', userId: 'user6', userName: 'Olivia Park', timestamp: getRelativeTime(36) },
    ],
    threads: [],
    currentConditions: {
      crowdLevel: 'Busy',
      atmosphere: 'Lively',
    },
    contentType: 'standard',
    subTheme: 'Coffee Shops',
    themeId: 'cafes',
    createdBy: 'user6',
    createdAt: getRelativeTime(384),
  },
  {
    id: 'c4',
    title: 'Ritual Coffee Roasters',
    description: 'Local favorite with outdoor seating',
    fullDescription: 'Specialty coffee roaster with a great patio. Popular spot for morning coffee and people watching.',
    photo: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800',
    photos: [
      'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800',
    ],
    category: 'Spot',
    activityType: 'solo',
    vibe: ['Relaxed', 'Casual'],
    timeContext: 'Morning',
    indoor: false,
    distance: '1.5 km',
    savedByCount: 312,
    likesCount: 534,
    commentsCount: 67,
    goodFor: ['Coffee', 'Relaxing', 'Reading'],
    location: 'Valencia Street',
    coordinates: { lat: 37.7622, lng: -122.4214 },
    costLevel: '$',
    averageRating: 4.6,
    totalRatings: 278,
    communityPhotos: [],
    threads: [],
    currentConditions: {
      crowdLevel: 'Moderate',
      atmosphere: 'Chill',
    },
    contentType: 'standard',
    subTheme: 'Coffee Shops',
    themeId: 'cafes',
    createdBy: 'user1',
    createdAt: getRelativeTime(456),
  },

  // PHOTOGRAPHY THEME (6+ activities)
  {
    id: '4',
    title: 'Golden Gate Viewpoint',
    description: 'Perfect spot for sunrise photography',
    fullDescription: 'This iconic viewpoint offers stunning views of the Golden Gate Bridge. Best visited at sunrise for optimal lighting.',
    photo: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800',
    photos: [
      'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800',
      'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800',
    ],
    category: 'Spot',
    activityType: 'solo',
    vibe: ['Scenic', 'Peaceful'],
    timeContext: 'Sunrise',
    indoor: false,
    distance: '3.7 km',
    savedByCount: 645,
    likesCount: 1123,
    commentsCount: 234,
    goodFor: ['Photography', 'Sightseeing'],
    location: 'Battery Spencer',
    coordinates: { lat: 37.8272, lng: -122.4816 },
    costLevel: 'Free',
    averageRating: 4.8,
    totalRatings: 520,
    communityPhotos: [
      { id: 'cp8', url: 'https://images.unsplash.com/photo-1449034446853-66c86144b0ad?w=400', userId: 'user2', userName: 'Sarah Chen', timestamp: getRelativeTime(12) },
      { id: 'cp9', url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400', userId: 'user8', userName: 'Sophia Taylor', timestamp: getRelativeTime(60) },
    ],
    threads: [],
    currentConditions: {
      crowdLevel: 'Quiet',
      atmosphere: 'Calm',
      lightCondition: 'Golden Hour',
    },
    specialMoment: 'Best at sunrise',
    contentType: 'standard',
    subTheme: 'Viewpoints',
    themeId: 'photography',
    createdBy: 'user2',
    createdAt: getRelativeTime(528),
  },
  {
    id: 'p2',
    title: 'Painted Ladies',
    description: 'Iconic Victorian houses',
    fullDescription: 'Classic San Francisco photo opportunity with the famous Painted Ladies and city skyline backdrop.',
    photo: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800',
    photos: [
      'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800',
    ],
    category: 'Spot',
    activityType: 'solo',
    vibe: ['Iconic', 'Touristy'],
    timeContext: 'Anytime',
    indoor: false,
    distance: '1.8 km',
    savedByCount: 489,
    likesCount: 823,
    commentsCount: 145,
    goodFor: ['Photography', 'Sightseeing', 'Architecture'],
    location: 'Alamo Square Park',
    coordinates: { lat: 37.7766, lng: -122.4330 },
    costLevel: 'Free',
    averageRating: 4.5,
    totalRatings: 367,
    communityPhotos: [],
    threads: [],
    currentConditions: {
      crowdLevel: 'Busy',
      atmosphere: 'Touristy',
    },
    contentType: 'standard',
    subTheme: 'Architecture',
    themeId: 'photography',
    createdBy: 'user8',
    createdAt: getRelativeTime(672),
  },
  {
    id: 'p3',
    title: 'Pier 7 Sunset',
    description: 'Bay Bridge views and city lights',
    fullDescription: 'Long pier perfect for sunset and night photography. Great spot for capturing the Bay Bridge lights.',
    photo: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800',
    photos: [
      'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800',
    ],
    category: 'Spot',
    activityType: 'solo',
    vibe: ['Scenic', 'Romantic'],
    timeContext: 'Sunset to night',
    indoor: false,
    distance: '2.4 km',
    savedByCount: 378,
    likesCount: 612,
    commentsCount: 98,
    goodFor: ['Photography', 'Sunset', 'Night shots'],
    location: 'Embarcadero',
    coordinates: { lat: 37.7988, lng: -122.3972 },
    costLevel: 'Free',
    averageRating: 4.7,
    totalRatings: 289,
    communityPhotos: [],
    threads: [],
    currentConditions: {
      crowdLevel: 'Low',
      atmosphere: 'Peaceful',
    },
    contentType: 'standard',
    subTheme: 'Golden Hour',
    themeId: 'photography',
    createdBy: 'user2',
    createdAt: getRelativeTime(768),
  },

  // SPORT THEME (7+ activities)
  {
    id: 's1',
    title: 'Yoga in the Park',
    description: 'Community yoga sessions every Saturday',
    fullDescription: 'Join the community for free yoga sessions in the park. All levels welcome. Bring your own mat.',
    photo: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800',
    photos: [
      'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800',
      'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800',
    ],
    category: 'Activity',
    activityType: 'active-social',
    vibe: ['Active', 'Social'],
    timeContext: 'Saturday mornings',
    indoor: false,
    distance: '1.2 km',
    savedByCount: 403,
    likesCount: 678,
    commentsCount: 145,
    goodFor: ['Exercise', 'Socializing', 'Wellness'],
    location: 'Golden Gate Park',
    coordinates: { lat: 37.7694, lng: -122.4862 },
    costLevel: 'Free',
    averageRating: 4.8,
    totalRatings: 245,
    communityPhotos: [],
    threads: [],
    currentConditions: {
      crowdLevel: 'Moderate',
      atmosphere: 'Energizing',
    },
    contentType: 'standard',
    subTheme: 'Yoga',
    themeId: 'sport',
    createdBy: 'user4',
    createdAt: getRelativeTime(144),
  },
  {
    id: 's2',
    title: 'Marina Green Workout',
    description: 'Outdoor fitness bootcamp',
    fullDescription: 'High-intensity outdoor workout with stunning bay views. Classes run weekday mornings.',
    photo: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800',
    photos: [
      'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800',
    ],
    category: 'Activity',
    activityType: 'active-social',
    vibe: ['Active', 'Intense'],
    timeContext: 'Weekday mornings',
    indoor: false,
    distance: '3.5 km',
    savedByCount: 267,
    likesCount: 445,
    commentsCount: 89,
    goodFor: ['Exercise', 'Fitness', 'Socializing'],
    location: 'Marina Green',
    coordinates: { lat: 37.8049, lng: -122.4362 },
    costLevel: '$15/class',
    averageRating: 4.6,
    totalRatings: 178,
    communityPhotos: [],
    threads: [],
    currentConditions: {
      crowdLevel: 'Moderate',
      atmosphere: 'Energetic',
    },
    contentType: 'standard',
    subTheme: 'Gyms',
    themeId: 'sport',
    createdBy: 'user3',
    createdAt: getRelativeTime(216),
  },
  {
    id: 's3',
    title: 'Embarcadero Running Route',
    description: 'Scenic waterfront running path',
    fullDescription: 'Popular running route along the waterfront with bay views. Flat, paved, and well-lit for early morning or evening runs.',
    photo: 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=800',
    photos: [
      'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=800',
    ],
    category: 'Route',
    activityType: 'solo',
    vibe: ['Active', 'Scenic'],
    timeContext: 'Anytime',
    indoor: false,
    distance: '6.4 km',
    savedByCount: 523,
    likesCount: 834,
    commentsCount: 167,
    goodFor: ['Running', 'Exercise', 'Views'],
    location: 'Embarcadero',
    coordinates: { lat: 37.7955, lng: -122.3937 },
    costLevel: 'Free',
    averageRating: 4.7,
    totalRatings: 356,
    communityPhotos: [],
    threads: [],
    currentConditions: {
      crowdLevel: 'Moderate',
      atmosphere: 'Active',
    },
    contentType: 'route',
    route: {
      distance: '6.4 km',
      duration: '30-45 min',
      difficulty: 'Easy',
      elevation: '10m',
      startPoint: 'Ferry Building',
      waypoints: [],
    },
    subTheme: 'Running Routes',
    themeId: 'sport',
    createdBy: 'user5',
    createdAt: getRelativeTime(312),
  },

  // SOCIAL THEME (5+ activities)
  {
    id: 'so1',
    title: 'Dolores Park Picnic',
    description: 'Popular gathering spot with city views',
    fullDescription: 'A vibrant park perfect for picnics and socializing. Features great views and plenty of space for groups.',
    photo: 'https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?w=800',
    photos: [
      'https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?w=800',
      'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800',
    ],
    category: 'Spot',
    activityType: 'active-social',
    vibe: ['Social', 'Relaxed'],
    timeContext: 'Afternoon',
    indoor: false,
    distance: '1.6 km',
    savedByCount: 725,
    likesCount: 1156,
    commentsCount: 289,
    goodFor: ['Picnic', 'Socializing', 'Relaxing'],
    location: 'Mission District',
    coordinates: { lat: 37.7596, lng: -122.4269 },
    costLevel: 'Free',
    averageRating: 4.7,
    totalRatings: 410,
    communityPhotos: [
      { id: 'cp10', url: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=400', userId: 'user1', userName: 'Jordan Smith', timestamp: getRelativeTime(18) },
    ],
    threads: [],
    currentConditions: {
      crowdLevel: 'Very Busy',
      atmosphere: 'Lively',
    },
    specialMoment: 'Weekends are buzzing',
    contentType: 'standard',
    subTheme: 'Meetups',
    themeId: 'social',
    createdBy: 'user1',
    createdAt: getRelativeTime(96),
  },
  {
    id: 'so2',
    title: 'Thursday Night Art Walk',
    description: 'Gallery openings and street art tour',
    fullDescription: 'Monthly art walk through the Mission with gallery openings, street art, and food trucks.',
    photo: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800',
    photos: [
      'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800',
    ],
    category: 'Activity',
    activityType: 'active-social',
    vibe: ['Social', 'Artistic'],
    timeContext: 'Thursday evenings',
    indoor: false,
    distance: '2.1 km',
    savedByCount: 456,
    likesCount: 789,
    commentsCount: 178,
    goodFor: ['Art', 'Socializing', 'Culture'],
    location: 'Mission District',
    coordinates: { lat: 37.7599, lng: -122.4148 },
    costLevel: 'Free',
    averageRating: 4.8,
    totalRatings: 267,
    communityPhotos: [],
    threads: [],
    currentConditions: {
      crowdLevel: 'Busy',
      atmosphere: 'Creative',
    },
    contentType: 'standard',
    subTheme: 'Events',
    themeId: 'social',
    createdBy: 'user8',
    createdAt: getRelativeTime(432),
  },

  // WATER THEME (5+ activities)
  {
    id: 'w1',
    title: 'Ocean Beach Sunset',
    description: 'Watch the waves and sunset',
    fullDescription: 'Beautiful beach perfect for sunset walks. The wide sandy beach offers plenty of space even on busy days.',
    photo: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
    photos: [
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
    ],
    category: 'Spot',
    activityType: 'solo',
    vibe: ['Peaceful', 'Scenic'],
    timeContext: 'Sunset',
    indoor: false,
    distance: '6.2 km',
    savedByCount: 589,
    likesCount: 967,
    commentsCount: 165,
    goodFor: ['Walking', 'Photography', 'Sunset'],
    location: 'Outer Sunset',
    coordinates: { lat: 37.7596, lng: -122.5107 },
    costLevel: 'Free',
    averageRating: 4.8,
    totalRatings: 365,
    communityPhotos: [],
    threads: [],
    currentConditions: {
      crowdLevel: 'Moderate',
      atmosphere: 'Peaceful',
      lightCondition: 'Golden Hour',
    },
    bestTimeToVisit: 'Sunset (6-8 PM)',
    contentType: 'standard',
    subTheme: 'Beaches',
    themeId: 'water',
    createdBy: 'user2',
    createdAt: getRelativeTime(504),
  },
  {
    id: 'w2',
    title: 'Aquatic Park Swimming',
    description: 'Bay swimming with stunning views',
    fullDescription: 'Protected cove perfect for open water swimming. Beautiful views of Alcatraz and the Golden Gate Bridge.',
    photo: 'https://images.unsplash.com/photo-1530213786676-41ad9f7736f6?w=800',
    photos: [
      'https://images.unsplash.com/photo-1530213786676-41ad9f7736f6?w=800',
    ],
    category: 'Spot',
    activityType: 'active-social',
    vibe: ['Active', 'Refreshing'],
    timeContext: 'Morning',
    indoor: false,
    distance: '4.3 km',
    savedByCount: 234,
    likesCount: 456,
    commentsCount: 89,
    goodFor: ['Swimming', 'Exercise', 'Views'],
    location: 'Fisherman\'s Wharf',
    coordinates: { lat: 37.8085, lng: -122.4242 },
    costLevel: 'Free',
    averageRating: 4.6,
    totalRatings: 178,
    communityPhotos: [],
    threads: [],
    currentConditions: {
      crowdLevel: 'Low',
      atmosphere: 'Invigorating',
      waterTemp: '58°F',
    },
    contentType: 'standard',
    subTheme: 'Pools',
    themeId: 'water',
    createdBy: 'user5',
    createdAt: getRelativeTime(624),
  },

  // ROUTES THEME (additional)
  {
    id: 'r1',
    title: 'Twin Peaks Sunset Hike',
    description: '360° views of the city',
    fullDescription: 'Popular hiking spot with panoramic city views. The trail is well-maintained and suitable for all fitness levels.',
    photo: 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=800',
    photos: [
      'https://images.unsplash.com/photo-1551632811-561732d1e306?w=800',
      'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800',
    ],
    category: 'Route',
    activityType: 'active-social',
    vibe: ['Active', 'Scenic'],
    timeContext: 'Sunset',
    indoor: false,
    distance: '4.1 km',
    savedByCount: 612,
    likesCount: 1045,
    commentsCount: 234,
    goodFor: ['Hiking', 'Photography', 'Views'],
    location: 'Twin Peaks',
    coordinates: { lat: 37.7544, lng: -122.4477 },
    costLevel: 'Free',
    averageRating: 4.9,
    totalRatings: 480,
    communityPhotos: [],
    threads: [],
    currentConditions: {
      crowdLevel: 'Busy',
      atmosphere: 'Energetic',
      lightCondition: 'Golden Hour',
    },
    bestTimeToVisit: 'Sunset (5-7 PM)',
    route: {
      distance: '2.5 km',
      duration: '45 min',
      difficulty: 'Moderate',
      elevation: '+150m',
      startPoint: 'Twin Peaks Parking',
      waypoints: [],
    },
    contentType: 'route',
    subTheme: 'Scenic Loops',
    themeId: 'routes',
    createdBy: 'user5',
    createdAt: getRelativeTime(336),
  },

  // SEASONAL & HIDDEN GEMS
  {
    id: 'se1',
    title: 'Cherry Blossom Festival',
    description: 'Annual spring celebration in Japantown',
    fullDescription: 'Beautiful cherry blossoms, cultural performances, and Japanese street food. Limited time event in spring.',
    photo: 'https://images.unsplash.com/photo-1522383225653-ed111181a951?w=800',
    photos: [
      'https://images.unsplash.com/photo-1522383225653-ed111181a951?w=800',
    ],
    category: 'Activity',
    activityType: 'passive-social',
    vibe: ['Cultural', 'Festive'],
    timeContext: 'Spring weekends',
    indoor: false,
    distance: '2.8 km',
    savedByCount: 834,
    likesCount: 1456,
    commentsCount: 312,
    goodFor: ['Culture', 'Photography', 'Food'],
    location: 'Japantown',
    coordinates: { lat: 37.7854, lng: -122.4306 },
    costLevel: 'Free (food extra)',
    averageRating: 4.9,
    totalRatings: 567,
    communityPhotos: [],
    threads: [],
    currentConditions: {
      crowdLevel: 'Very Busy',
      atmosphere: 'Festive',
    },
    specialMoment: 'Peak bloom mid-April',
    contentType: 'standard',
    subTheme: 'Spring',
    themeId: 'seasonal',
    createdBy: 'user6',
    createdAt: getRelativeTime(168),
  },
  {
    id: 'h1',
    title: 'Marshall Beach',
    description: 'Secret beach under the Golden Gate',
    fullDescription: 'Hidden beach with stunning views of the Golden Gate Bridge. Requires a short hike down. Often less crowded.',
    photo: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
    photos: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
    ],
    category: 'Spot',
    activityType: 'solo',
    vibe: ['Quiet', 'Hidden'],
    timeContext: 'Low tide',
    indoor: false,
    distance: '5.7 km',
    savedByCount: 178,
    likesCount: 289,
    commentsCount: 45,
    goodFor: ['Photography', 'Relaxing', 'Solitude'],
    location: 'Presidio',
    coordinates: { lat: 37.8072, lng: -122.4715 },
    costLevel: 'Free',
    averageRating: 4.8,
    totalRatings: 134,
    communityPhotos: [],
    threads: [],
    currentConditions: {
      crowdLevel: 'Very Low',
      atmosphere: 'Secluded',
    },
    specialMoment: 'Best at low tide',
    contentType: 'standard',
    subTheme: 'Local Secrets',
    themeId: 'hidden',
    createdBy: 'user2',
    createdAt: getRelativeTime(792),
  },
];

const themes = [
  {
    id: 'nature',
    name: 'Nature',
    shortDescription: 'Outdoors & Parks',
    description: 'Explore outdoor spots and scenic locations',
    image: 'https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?w=600',
    gradient: 'from-green-400 to-emerald-600',
    icon: '🌲',
    subThemes: ['Hikes', 'Forest Walks', 'Scenic Views', 'Lakes & Swim', 'Sunset Spots', 'Day Hikes'],
    activityCount: activities.filter(a => a.themeId === 'nature').length,
  },
  {
    id: 'sport',
    name: 'Sport',
    shortDescription: 'Fitness & Activity',
    description: 'Find fitness activities and workout spots',
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600',
    gradient: 'from-orange-400 to-red-600',
    icon: '⚽',
    subThemes: ['Gyms', 'Yoga', 'Running Routes', 'Sports Fields', 'Climbing'],
    activityCount: activities.filter(a => a.themeId === 'sport').length,
  },
  {
    id: 'photography',
    name: 'Photography',
    shortDescription: 'Viewpoints & Shots',
    description: 'Discover the best spots for photos',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600',
    gradient: 'from-purple-400 to-pink-600',
    icon: '📸',
    subThemes: ['Viewpoints', 'Architecture', 'Street', 'Nature', 'Golden Hour'],
    activityCount: activities.filter(a => a.themeId === 'photography').length,
  },
  {
    id: 'cafes',
    name: 'Cafés & Study',
    shortDescription: 'Coffee & Work',
    description: 'Cozy spots for coffee and work',
    image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600',
    gradient: 'from-amber-400 to-orange-600',
    icon: '☕',
    subThemes: ['Coffee Shops', 'Study Spots', 'Co-working', 'Quiet Cafés', 'WiFi'],
    activityCount: activities.filter(a => a.themeId === 'cafes').length,
  },
  {
    id: 'social',
    name: 'Social',
    shortDescription: 'Meetups & Events',
    description: 'Meet people and join group activities',
    image: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=600',
    gradient: 'from-blue-400 to-cyan-600',
    icon: '🎉',
    subThemes: ['Meetups', 'Events', 'Group Activities', 'Social Sports', 'Workshops'],
    activityCount: activities.filter(a => a.themeId === 'social').length,
  },
  {
    id: 'water',
    name: 'Water & Swim',
    shortDescription: 'Lakes & Beaches',
    description: 'Swimming and water activities',
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600',
    gradient: 'from-cyan-400 to-blue-600',
    icon: '🏊',
    subThemes: ['Lakes', 'Beaches', 'Pools', 'Rivers', 'Water Sports'],
    activityCount: activities.filter(a => a.themeId === 'water').length,
  },
  {
    id: 'routes',
    name: 'Routes & Hikes',
    shortDescription: 'Trails & Walks',
    description: 'Walking and hiking trails',
    image: 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=600',
    gradient: 'from-teal-400 to-green-600',
    icon: '🥾',
    subThemes: ['Easy Walks', 'Day Hikes', 'Mountain Trails', 'Urban Routes', 'Scenic Loops'],
    activityCount: activities.filter(a => a.themeId === 'routes').length,
  },
  {
    id: 'seasonal',
    name: 'Seasonal',
    shortDescription: 'Limited Time',
    description: 'Limited-time activities and experiences',
    image: 'https://images.unsplash.com/photo-1476820865390-c52aeebb9891?w=600',
    gradient: 'from-rose-400 to-pink-600',
    icon: '🍂',
    subThemes: ['Winter', 'Spring', 'Summer', 'Fall', 'Festivals'],
    activityCount: activities.filter(a => a.themeId === 'seasonal').length,
  },
  {
    id: 'hidden',
    name: 'Hidden Gems',
    shortDescription: 'Off the Beaten Path',
    description: 'Off-the-beaten-path discoveries',
    image: 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=600',
    gradient: 'from-indigo-400 to-purple-600',
    icon: '💎',
    subThemes: ['Local Secrets', 'Quiet Spots', 'Undiscovered', 'Unique', 'Insider Tips'],
    activityCount: activities.filter(a => a.themeId === 'hidden').length,
  },
];

const users = {
  currentUser: {
    id: 'user1',
    name: 'Jordan Smith',
    username: '@jordansmith',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jordan',
    bio: 'Exploring the city one adventure at a time ✨',
    joinDate: '2024-08-15',
    city: 'San Francisco',
    interests: ['Photography', 'Hiking', 'Coffee', 'Nature'],
    isOwnProfile: true,
    followersCount: 342,
    followingCount: 189,
    stats: {
      photos: 24,
      activities: 12,
      threads: 8,
    },
  },
};

const messages = [
  {
    activityId: '1',
    messages: [
      {
        id: '1',
        userId: 'user2',
        userName: 'Sarah Chen',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
        message: 'Hey! Planning to go this weekend, anyone interested?',
        timestamp: '10:30 AM',
        createdAt: getRelativeTime(2),
      },
      {
        id: '2',
        userId: 'user3',
        userName: 'Alex Martinez',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
        message: 'I\'m down! What time were you thinking?',
        timestamp: '10:45 AM',
        createdAt: getRelativeTime(1.75),
      },
      {
        id: '3',
        userId: 'user2',
        userName: 'Sarah Chen',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
        message: 'Around 9 AM? The weather looks perfect ☀️',
        timestamp: '10:47 AM',
        createdAt: getRelativeTime(1.7),
      },
      {
        id: '4',
        userId: 'user1',
        userName: 'Jordan Smith',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jordan',
        message: 'Can I join too? First time trying this!',
        timestamp: '11:02 AM',
        createdAt: getRelativeTime(1.5),
      },
      {
        id: '5',
        userId: 'user3',
        userName: 'Alex Martinez',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
        message: 'Of course! We can meet at the entrance',
        timestamp: '11:15 AM',
        createdAt: getRelativeTime(1.25),
      },
    ],
  },
  {
    activityId: '3',
    messages: [
      {
        id: '6',
        userId: 'user4',
        userName: 'Emma Wilson',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
        message: 'Great spot! I\'ll be there today',
        timestamp: '1 hour ago',
        createdAt: getRelativeTime(1),
      },
      {
        id: '7',
        userId: 'user7',
        userName: 'David Kim',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
        message: 'WiFi password still the same?',
        timestamp: '45 mins ago',
        createdAt: getRelativeTime(0.75),
      },
    ],
  },
  {
    activityId: 's1',
    messages: [
      {
        id: '8',
        userId: 'user4',
        userName: 'Emma Wilson',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
        message: 'See you all tomorrow morning! 🧘‍♀️',
        timestamp: '6:30 PM',
        createdAt: getRelativeTime(14),
      },
      {
        id: '9',
        userId: 'user5',
        userName: 'Marcus Johnson',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Marcus',
        message: 'Looking forward to it! Should I bring anything?',
        timestamp: '6:45 PM',
        createdAt: getRelativeTime(13.75),
      },
      {
        id: '10',
        userId: 'user4',
        userName: 'Emma Wilson',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
        message: 'Just your mat and water bottle 💧',
        timestamp: '6:50 PM',
        createdAt: getRelativeTime(13.6),
      },
    ],
  },
];

const savedActivities = [
  activities.find(a => a.id === '1'),
  activities.find(a => a.id === '4'),
  activities.find(a => a.id === 'r1'),
  activities.find(a => a.id === 'c3'),
];

module.exports = {
  activities,
  themes,
  users,
  userProfiles,
  messages,
  savedActivities,
  getRelativeTime,
};
